## Antibody Modelling Function for human (179 Individuals)
## Create S-Fig-4


######### Load shared functions & required packages ############
```{r}
source("functions.R")

required_packages <- c('dplyr', 'deSolve', 'ggplot2','purrr')
install_and_load(required_packages)
```

######## Set time range ###########
```{r}
Tmin <- 0
Tmax <- 180 
step_size <- 0.005
times<-c(seq(Tmin,Tmax,step_size))
```

#######Read individual data#########
```{r}
original <- read.csv("demo_data_human.csv")
#note: this data is not provided.
Est <- read.csv("estimatedIndividualParameters_human.txt",  sep = ",", comment.char = "", header = T)
Simulated <- read.csv("simulatedIndividualParameters_human.txt" ,sep = ",", comment.char = "", header = T)
max(Simulated$rep) #See how many simulated parameters for each individual
```
####### Compute individual fits ########
## ind_fit_human() is defined in functions.R (uses ode_ab_pop and globals times/Tmin/Tmax/step_size).
```{r}
individual_fit <- ind_fit_human(Est, Simulated)
```

######################################
############ S-Fig-4##################
######################################

```{r}
individual_fit_with_code <- individual_fit %>% rename(id = Code) %>% left_join(original[,c(1,5)], by = "id")

pdf("individual_plots_2.pdf", 14, 14)

for (i in seq(1, length(unique(individual_fit_with_code$Code)),length(unique(individual_fit_with_code$Code)))) {
  print(
   ggplot(individual_fit_with_code, aes(x = Days)) +
   geom_ribbon(aes(ymin = Min, ymax = Max), alpha = 0.3) +
   geom_line(aes(y = y), size = 1, alpha = 0.8) +
   geom_point(data = original, aes(x = day, y = igG), 
             shape = 16, size = 2, alpha = 2) +
  facet_wrap(~Code) +
  labs(
    title = "Individual Fit with Shaded Uncertainty",
    x = "Days",
    y = "IgG Binding %"
   
  ) +
 theme(axis.text = element_text(colour = "black"),
        axis.ticks = element_line(colour = "black"),
        axis.line = element_line(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        legend.position='none',
        axis.title.y = element_text(size=11,family="sans"),
        axis.title.x = element_text(size=11,family="sans"),
  theme_minimal() ))
  }
dev.off()
```
